version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - ".:/app"
    image:
      vladislav1923/devops-for-programmers-project-lvl1