version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "make setup && make dev"
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"