name: push-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cd app && npm install && make ci

      - name: Build docker image
        run: cd app && make docker-build

      - name: Push docker image
        run: cd app && make docker-push
