name: push-check

on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  tests:
    steps:
      run: cd app && npm install && make ci
    needs: setup
  build:
    steps:
      run: cd app && make docker-build
    needs: setup
  push:
    steps:
      run: cd app && make docker-push
    needs: build

