name: push-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run tests
        run: cd app && npm install && make ci

      - name: build docker image
        run: make docker-build

      - name: push docker image
        run: make docker-push
